Projet/EFCProject/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCProject.Data;
using EFCProject.Models;
using Microsoft.AspNetCore.Authorization;
using static System.Formats.Asn1.AsnWriter;
using System.Reflection;
using System.IO;
using System.Collections;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.IdentityModel.Tokens;
using NuGet.Protocol.Plugins;
using System.Globalization;
using System.Linq.Expressions;
using System.Security.Permissions;
using System.Security.Claims;

namespace EFCProject.Controllers
{
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<GamesController> _logger;
        private readonly IWebHostEnvironment _environment;


        public GamesController(ApplicationDbContext context, ILogger<GamesController> logger, IWebHostEnvironment environment)
        {
            _context = context;
            _logger = logger;
            _environment = environment;
        }

		// GET: Games

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Index()
        {
            return _context.Game != null ?
                        View(await _context.Game.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Game'  is null.");
        }
		[Authorize(Roles = "Producer")]
		public async Task<IActionResult> IndexProd()
		{
			return _context.Game != null ?
						View(await _context.Game.ToListAsync()) :
						Problem("Entity set 'ApplicationDbContext.Game'  is null.");
		}

		// GET: Games/ShowSearchForm
		public async Task<IActionResult> ShowSearchForm(string origine)
        {   
           
            
            return _context.Game != null ?
                                View(await _context.Game.ToListAsync()) :
                                Problem("Entity set 'ApplicationDbContext.Game'  is null.");
        }
        //POST : Games/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string SearchInput, string origine)
        {
            if (origine == null)
            {
                origine = "ShowSearchForm";
            }

            Type type = typeof(Game);
            if (SearchInput != null)
            {
                // Obtenez les propriétés de l'objet Game
                PropertyInfo[] properties = type.GetProperties();
                List<Game> tabGame = await _context.Game.ToListAsync();
                List<Game> vide = new List<Game>();
                foreach (Game game in tabGame)
                {
                    foreach (PropertyInfo property in properties)
                    {
                        Type propertyType = property.PropertyType;

                        if (propertyType == typeof(string))
                        {
                            string propertyValue = (string)property.GetValue(game);
                            if (propertyValue != null && propertyValue.Contains(SearchInput))
                            {
                                vide.Add(game);
                            }

                        }
                    }
                }
                return View(origine, vide);
            }
            return View(origine, await _context.Game.ToListAsync());

        }
        public async Task<IActionResult> ShowSearchResultsProd(string SearchInput)
        {

            Type type = typeof(Game);
            if (SearchInput != null)
            {
                // Obtenez les propriétés de l'objet Game
                PropertyInfo[] properties = type.GetProperties();
                List<Game> tabGame = await _context.Game.ToListAsync();
                List<Game> vide = new List<Game>();
                foreach (Game game in tabGame)
                {
                    foreach (PropertyInfo property in properties)
                    {
                        Type propertyType = property.PropertyType;
                        if (propertyType == typeof(string))
                        {
                            string propertyValue = (string)property.GetValue(game);
                            if (propertyValue != null && propertyValue.Contains(SearchInput))
                            {
                                vide.Add(game);
                            }

                        }
                    }
                }
                return View("IndexProd", vide);
            }
            return View("IndexProd", await _context.Game.ToListAsync());
        }



        [Authorize]
		public async Task<IActionResult> Displayfav()
        {


            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
                

                // Effectuer une jointure entre les tables User et FavoriteGame
                var query = from game in _context.Game
                            join favorite in _context.Favorit on game.Id equals favorite.GameId
                            where favorite.UserId == userIdClaim.Value
                            select game;

                // Exécutez la requête et récupérez les résultats
                var favoriteGames = query.ToList();

                return favoriteGames != null ?
                    View("Displayfav", favoriteGames) :
                    Problem("Entity set 'ApplicationDbContext.Game'  is null.");
            }

            return View("../Account/Register");


        }

        
        [Authorize]
        [HttpPost]
        public IActionResult AddFav(int gameId, int userID ,string origin)
        {
            // Récupérez le jeu à partir de la base de données
            var game = _context.Game.Find(gameId);

            
            // Incrémentez le Score
             game.Score++;

            // Enregistrez les modifications dans la base de données
            _context.SaveChanges();

            // Vous pouvez renvoyer quelque chose en réponse si nécessaire
            return Json(new { success = true, newScore = game.Score });
        }


        public async Task<IActionResult> DisplayGamesInTab()
        {
            return _context.Game != null ?
                          View(await _context.Game.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Game'  is null.");
        }


        public async Task<IActionResult> DisplayGamesSorted(string sortBy, string origine)
        {
            
            if(origine == null)
            {
                origine = "ShowSearchForm";
            }
            Type type = typeof(Game);

            // Obtenez les propriétés de l'objet Game
            PropertyInfo[] properties = type.GetProperties();

            foreach (PropertyInfo property in properties)
            {
                if (property.Name == sortBy)
                {

                    List<Game> tabGame = await _context.Game.ToListAsync();
                    //List<Game> SortedList = tabGame.OrderBy(o => property.GetValue(o, null)).ToList();
					List<Game> SortedList = tabGame.OrderByDescending(o => property.GetValue(o, null)).ToList();
                    
					return View(origine, SortedList);
  
                }
            }
            return View(origine, await _context.Game.ToListAsync());
        }




        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
                        
            if (id == null || _context.Game == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            int isFavorite = 0;
            // Obtenez l'ID de l'utilisateur actuel (assurez-vous que votre application gère correctement l'authentification)
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
                if(userIdClaim != null)
                {
                    // Vérifiez si le jeu est déjà en favori pour cet utilisateur
                    if(_context.Favorit.Any(f => f.UserId == userIdClaim.Value && f.GameId == id))
                    {
                       isFavorite = 1;

					}

				}
                
            }
            var viewModel = new GameViewModel
            {
                Game = game,
                IsInFavorites = isFavorite
            };

            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [RequestFormLimits(MultipartBodyLengthLimit = 209715200)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Studio,Support,Size,Score,Engine,CreateDate,EndDate,Budget,Statut,Type,Image")] Game game, IFormFile postedFile)
        {
            game.Score = 0;
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    string path = _environment.WebRootPath + "/Asset/Images/Games/";

Projet/EFCProject/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCProject.Data;
using EFCProject.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace EFCProject.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MessagesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Messages
        [Authorize(Roles = "CommManager")]
        public async Task<IActionResult> Index()
        {
              return _context.Message != null ? 
                          View(await _context.Message.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Message'  is null.");
        }

        // GET: Messages/Details/5
        [Authorize(Roles = "CommManager")]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null || _context.Message == null)
            {
                return NotFound();
            }

            var message = await _context.Message
                .FirstOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            return View();
        }

		public IActionResult Display()
		{
			// Récupérer les 5 derniers messages (exemple avec Entity Framework Core)
			var latestMessages = _context.Message
				.OrderByDescending(m => m.Date) // Assurez-vous d'ajuster selon votre modèle de données
				.Take(3)
				.ToList();

			// Retourner les messages au format JSON
			return Json(latestMessages);
		}

		[Authorize(Roles = "CommManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Text,UserName,Date")] Message message)
        {

            message.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Add(message);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        // POST: Messages/Delete/5
        [Authorize(Roles = "CommManager")]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Message == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Message'  is null.");
            }
            var message = await _context.Message.FindAsync(id);
            if (message != null)
            {
                _context.Message.Remove(message);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
          return (_context.Message?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Projet/EFCProject/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCProject.Data;
using EFCProject.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using NuGet.Protocol.Plugins;

namespace EFCProject.Controllers
{
    public class UserController : Controller
    {


        private readonly EFCProject.Data.ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public UserController(ApplicationDbContext context, 
								UserManager<ApplicationUser> userManager ,
								RoleManager<IdentityRole> roleManager ,
								SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
			_roleManager = roleManager;
			_signInManager = signInManager;


        }

        
		[HttpGet]
        public async Task<IActionResult> ListUsers(string roleTri)
        {
			var users = await _userManager.Users.ToListAsync();

			if (string.IsNullOrEmpty(roleTri))
			{
				// Si roleTri est null ou vide, afficher tous les utilisateurs
				users = await _userManager.Users.ToListAsync();
			}
			else
			{
				// Si roleTri est spécifié, filtrer les utilisateurs par rôle
				var usersInRole = await _userManager.GetUsersInRoleAsync(roleTri);
				users = usersInRole.ToList();
			}

			List<UserViewModel> model = new List<UserViewModel>();

            foreach (ApplicationUser user in users)
            {
                UserViewModel userViewModel = new UserViewModel
                {
                    User = user,
                    Roles = await _userManager.GetRolesAsync(user)


                };

                model.Add(userViewModel);
			}
			return View(model); 
        }
		
		[HttpPost]
		public async Task<IActionResult> EditUsersInRole(string roleName, string userId )
        {   
            
			var user = await _userManager.FindByIdAsync(userId);
			if (user == null)
			{
				ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
				return View("NotFound");
			}

			if (!await _roleManager.RoleExistsAsync(roleName))
			{
				
				// Si le rôle n'existe pas, vous pouvez le créer ici
				var role = new IdentityRole(roleName);
				await _roleManager.CreateAsync(role);
				return View("NotFound");
			}

			var userRoles = await _userManager.GetRolesAsync(user);
			await _userManager.RemoveFromRolesAsync(user, userRoles);
			// Ajoutez l'utilisateur au rôle
			await _userManager.AddToRoleAsync(user, roleName);

			return Json(new { success = true, role = roleName });
		}


		public async Task<IActionResult> EditPasword(string userId, string currentPassword, string newPassword)
		{
			var user = await _userManager.FindByIdAsync(userId);
			if (user == null)
			{
				return NotFound($"ID introuvable : '{_userManager.GetUserId(User)}'.");
			}
			var changePasswordResult = await _userManager.ChangePasswordAsync(user, currentPassword, newPassword);
			if (changePasswordResult.Succeeded)
			{
				await _signInManager.RefreshSignInAsync(user);
				//return View("ListUsers", _userManager.Users.ToListAsync());
				return Json(new { success = true, newPassword = newPassword });
			}
			else
			{
				foreach (var error in changePasswordResult.Errors)
				{
					ModelState.AddModelError(string.Empty, error.Description);
				}
				return Json(new { success = false, newPassword = newPassword });
				//return View("ListUsers", _userManager.Users.ToListAsync());
            }
		}


	}
}

Projet/EFCProject/Views/Shared/_GameInTab.cshtml
@model IEnumerable<EFCProject.Models.Game>

    
<div class="image-grid">
    @foreach (var game in Model)
    {      
        <a class="jeu-grid" href="@Url.Action("Details", "Games", new { id = game.Id })" style="background-image: url('@Url.Content("~/Asset/Images/Games/" + game.Image)')">
            <div class="game-pres">
                <h2 class="game-pres-header"><span>@game.Title</span></h2>
                <p class="game-pres-content">@game.Description</p>
            </div>
        </a>
    }
</div>

Projet/EFCProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity


@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFCProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFCProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header id ="top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  box-shadow">
            <div class="container-fluid mx-2 container mx-auto ">

                <a id="Logo-contain" class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="logo" src="~/Asset/Images/LogoFrenchGame.png" width="90" height="90" />
                 </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav my-3 py-3 mx-2 bordered-lu">
                        <li class="navbar-button">
                            <a asp-area="" asp-controller="Games" asp-action="ShowSearchForm">Liste Jeux</a>
                        </li>
                        <li class="navbar-button">
                            <a  asp-area="" asp-controller="Games" asp-action="Displayfav">Favoris</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="navbar-button">
                                <a asp-area="" asp-controller="Games" asp-action="Index">Page Admin</a>
                            </li>
                            <li class="navbar-button">
                                <a  asp-area="" asp-controller="User" asp-action="ListUsers">Liste Users</a>
                            </li>
                        }
                        @if (User.IsInRole("Producer"))
                        {
                            <li class="navbar-button">
                                <a  asp-area="" asp-controller="Games" asp-action="IndexProd">Page Producteur </a>
                            </li>
                        }
                        @if (User.IsInRole("CommManager"))
                        {
                            <li class="navbar-button">
                                <a  asp-area="" asp-controller="Messages" asp-action="Index">Page CommManager</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    
    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="">
        <div class="container navbar mt-3">
            2023 - EFCProject - <a href="#top">Remonter</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>