Projet/EFCProject/Models/Game.cs
using System.Drawing;
using System.ComponentModel.DataAnnotations;



namespace EFCProject.Models
{
    public class Game
    {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Studio { get; set; }
        public string? Support { get; set; }
        public float Size { get; set; }    
        public int Score { get; set; }
        public string? Engine { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime EndDate { get; set; }
        public float Budget { get; set; }
        public string? Statut { get; set; }
        public string? Type { get; set; }
        public string? Image { get; set; }

        public Game()
        {
            
        }

    }
}

Projet/EFCProject/Models/GameViewModel.cs
namespace EFCProject.Models
{
    public class GameViewModel
    {
        public Game Game { get; set; }
        public int IsInFavorites { get; set; }
    }
}

Projet/EFCProject/Controllers/FavoritsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCProject.Data;
using EFCProject.Models;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;


namespace EFCProject.Controllers
{
    public class FavoritsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<GamesController> _logger;

        public FavoritsController(ApplicationDbContext context, ILogger<GamesController> logger )
        {
            _context = context;
            _logger = logger;

        }

		// GET: Favorits
		[Authorize]
		public async Task<IActionResult> Index()
        {
              return _context.Favorit != null ? 
                          View(await _context.Favorit.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Favorit'  is null.");
        }

        // GET: Favorits/Details/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details()
        {

            //string userID = Membership.GetUser().ProviderUserKey.ToString();
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                // the principal identity is a claims identity.
                // now we need to find the NameIdentifier claim
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    var userIdValue = userIdClaim.Value;
    

                    return Json(new { success = true, userId = userIdValue });
                }
            }



            return Json(new { success = false, userId = "non" });
        }

		[Authorize]
		[HttpPost]
        public async Task<IActionResult> AddFav(int gameId)
        {
            Favorit favorit = new Favorit();
            
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    favorit.UserId = userIdClaim.Value;
                    favorit.GameId = gameId;
                    if (ModelState.IsValid)
                    {
                        _context.Add(favorit);
                        _context.Game.Find(gameId).Score++;
                        await _context.SaveChangesAsync();
                        return Json(new { success = true, score = _context.Game.Find(gameId).Score });
                    }

                    
                }
		    }
            return View("../Account/Register");
        }

		[Authorize]
		[HttpDelete]
        public async Task<IActionResult> RemFav(int gameId)
        {

            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);

                if (userIdClaim != null)
                {
                    var supprFav = _context.Favorit.FirstOrDefault(f => f.GameId == gameId && f.UserId == userIdClaim.Value);
                    _context.Favorit.Remove(supprFav);    
                    _context.Game.Find(gameId).Score--;
                    await _context.SaveChangesAsync();

  

                    return Json(new { success = true , score = _context.Game.Find(gameId).Score });
                }
            }
            return View("../../Account/Register");
        }

		/*

        // GET: Favorits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Favorit == null)
            {
                return NotFound();
            }

            var favorit = await _context.Favorit.FindAsync(id);
            if (favorit == null)
            {
                return NotFound();
            }
            return View(favorit);
        }

        // POST: Favorits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,GameId")] Favorit favorit)
        {
            if (id != favorit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favorit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoritExists(favorit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(favorit);
        }

        // GET: Favorits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Favorit == null)
            {
                return NotFound();
            }

            var favorit = await _context.Favorit
                .FirstOrDefaultAsync(m => m.Id == id);
            if (favorit == null)
            {
                return NotFound();
            }

            return View(favorit);
        }

        // POST: Favorits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Favorit == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Favorit'  is null.");
            }
            var favorit = await _context.Favorit.FindAsync(id);
            if (favorit != null)
            {
                _context.Favorit.Remove(favorit);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavoritExists(int id)
        {
          return (_context.Favorit?.Any(e => e.Id == id)).GetValueOrDefault();
        }*/
	}
}

Projet/EFCProject/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFCProject.Data;
using EFCProject.Models;
using Microsoft.AspNetCore.Authorization;
using static System.Formats.Asn1.AsnWriter;
using System.Reflection;
using System.IO;
using System.Collections;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.IdentityModel.Tokens;
using NuGet.Protocol.Plugins;
using System.Globalization;
using System.Linq.Expressions;
using System.Security.Permissions;
using System.Security.Claims;

namespace EFCProject.Controllers
{
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<GamesController> _logger;
        private readonly IWebHostEnvironment _environment;


        public GamesController(ApplicationDbContext context, ILogger<GamesController> logger, IWebHostEnvironment environment)
        {
            _context = context;
            _logger = logger;
            _environment = environment;
        }

		// GET: Games

		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> Index()
        {
            return _context.Game != null ?
                        View(await _context.Game.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Game'  is null.");
        }
		[Authorize(Roles = "Producer")]
		public async Task<IActionResult> IndexProd()
		{
			return _context.Game != null ?
						View(await _context.Game.ToListAsync()) :
						Problem("Entity set 'ApplicationDbContext.Game'  is null.");
		}

		// GET: Games/ShowSearchForm
		public async Task<IActionResult> ShowSearchForm(string origine)
        {   
           
            
            return _context.Game != null ?
                                View(await _context.Game.ToListAsync()) :
                                Problem("Entity set 'ApplicationDbContext.Game'  is null.");
        }
        //POST : Games/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string SearchInput, string origine)
        {
            if (origine == null)
            {
                origine = "ShowSearchForm";
            }

            Type type = typeof(Game);
            if (SearchInput != null)
            {
                // Obtenez les propriétés de l'objet Game
                PropertyInfo[] properties = type.GetProperties();
                List<Game> tabGame = await _context.Game.ToListAsync();
                List<Game> vide = new List<Game>();
                foreach (Game game in tabGame)
                {
                    foreach (PropertyInfo property in properties)
                    {
                        Type propertyType = property.PropertyType;

                        if (propertyType == typeof(string))
                        {
                            string propertyValue = (string)property.GetValue(game);
                            if (propertyValue != null && propertyValue.Contains(SearchInput))
                            {
                                vide.Add(game);
                            }

                        }
                    }
                }
                return View(origine, vide);
            }
            return View(origine, await _context.Game.ToListAsync());

        }
        public async Task<IActionResult> ShowSearchResultsProd(string SearchInput)
        {

            Type type = typeof(Game);
            if (SearchInput != null)
            {
                // Obtenez les propriétés de l'objet Game
                PropertyInfo[] properties = type.GetProperties();
                List<Game> tabGame = await _context.Game.ToListAsync();
                List<Game> vide = new List<Game>();
                foreach (Game game in tabGame)
                {
                    foreach (PropertyInfo property in properties)
                    {
                        Type propertyType = property.PropertyType;
                        if (propertyType == typeof(string))
                        {
                            string propertyValue = (string)property.GetValue(game);
                            if (propertyValue != null && propertyValue.Contains(SearchInput))
                            {
                                vide.Add(game);
                            }

                        }
                    }
                }
                return View("IndexProd", vide);
            }
            return View("IndexProd", await _context.Game.ToListAsync());
        }



        [Authorize]
		public async Task<IActionResult> Displayfav()
        {


            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
                

                // Effectuer une jointure entre les tables User et FavoriteGame
                var query = from game in _context.Game
                            join favorite in _context.Favorit on game.Id equals favorite.GameId
                            where favorite.UserId == userIdClaim.Value
                            select game;

                // Exécutez la requête et récupérez les résultats
                var favoriteGames = query.ToList();

                return favoriteGames != null ?
                    View("Displayfav", favoriteGames) :
                    Problem("Entity set 'ApplicationDbContext.Game'  is null.");
            }

            return View("../Account/Register");


        }

        
        [Authorize]
        [HttpPost]
        public IActionResult AddFav(int gameId, int userID ,string origin)
        {
            // Récupérez le jeu à partir de la base de données
            var game = _context.Game.Find(gameId);

            
            // Incrémentez le Score
             game.Score++;

            // Enregistrez les modifications dans la base de données
            _context.SaveChanges();

            // Vous pouvez renvoyer quelque chose en réponse si nécessaire
            return Json(new { success = true, newScore = game.Score });
        }


        public async Task<IActionResult> DisplayGamesInTab()
        {
            return _context.Game != null ?
                          View(await _context.Game.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Game'  is null.");
        }


        public async Task<IActionResult> DisplayGamesSorted(string sortBy, string origine)
        {
            
            if(origine == null)
            {
                origine = "ShowSearchForm";
            }
            Type type = typeof(Game);

            // Obtenez les propriétés de l'objet Game
            PropertyInfo[] properties = type.GetProperties();

            foreach (PropertyInfo property in properties)
            {
                if (property.Name == sortBy)
                {

                    List<Game> tabGame = await _context.Game.ToListAsync();
                    //List<Game> SortedList = tabGame.OrderBy(o => property.GetValue(o, null)).ToList();
					List<Game> SortedList = tabGame.OrderByDescending(o => property.GetValue(o, null)).ToList();
                    
					return View(origine, SortedList);
  
                }
            }
            return View(origine, await _context.Game.ToListAsync());
        }




        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
                        
            if (id == null || _context.Game == null)
            {
                return NotFound();
            }

            var game = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            int isFavorite = 0;
            // Obtenez l'ID de l'utilisateur actuel (assurez-vous que votre application gère correctement l'authentification)
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var userIdClaim = claimsIdentity.Claims
                    .FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
                if(userIdClaim != null)
                {
                    // Vérifiez si le jeu est déjà en favori pour cet utilisateur
                    if(_context.Favorit.Any(f => f.UserId == userIdClaim.Value && f.GameId == id))
                    {
                       isFavorite = 1;

					}

				}
                
            }
            var viewModel = new GameViewModel
            {
                Game = game,
                IsInFavorites = isFavorite
            };

            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [RequestFormLimits(MultipartBodyLengthLimit = 209715200)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Studio,Support,Size,Score,Engine,CreateDate,EndDate,Budget,Statut,Type,Image")] Game game, IFormFile postedFile)
        {
            game.Score = 0;
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    string path = _environment.WebRootPath + "/Asset/Images/Games/";

Projet/EFCProject/Views/Games/Details.cshtml
@model EFCProject.Models.GameViewModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Details";
}
@using Microsoft.AspNetCore.Identity

<div class="mt-3">
    <div class="col-md-10 offset-md-1 contente  mt-3">
        <h1>@Html.DisplayFor(model => model.Game.Title)</h1>

        <div>
            <div class="d-flex justify-content-start">
  

                    <button id="remFromFavoritesBtn" class="game-button" type="submit">Retiré des fav</button>

                    <button id="addToFavoritesBtn" class="game-button" type="submit">Ajouté au fav</button>
                    <h4 style="margin-left:15px" id="scoreUpdate" >Score : @Html.DisplayFor(model => model.Game.Score)</h4>
 
            </div>
            
                <div>
                @if (User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-route-id="@Model?.Game.Id">Modifier le jeu</a>
                }
                @if (User.IsInRole("Admin"))
                {
                    <a asp-action="Index">Retour a la liste</a>
                }
                else
                {
                    <a asp-action="ShowSearchForm">Retour a la liste</a>
                }
                
                </div>
            
            <hr />

        </div>
    </div>

 
    <div class="col-md-10 offset-md-1 contente  mt-3">
        <div class="row p-5">
            <div class="form-group col-md-6 text-right ">
                <h2>à propos de @Html.DisplayFor(model => model.Game.Title) </h2>
                <br/>
                <p>@Html.DisplayFor(model => model.Game.Description)</p>

                <hr />

                <p>Studio : @Html.DisplayFor(model => model.Game.Studio)</p>

                <p>Support : @Html.DisplayFor(model => model.Game.Support)</p>

                <p>GameEngine : @Html.DisplayFor(model => model.Game.Engine)</p>

                <p>Statut : @Html.DisplayFor(model => model.Game.Statut)</p>

                <p>Type : @Html.DisplayFor(model => model.Game.Type)</p>


            </div>

            <div class="form-group col-md-6">
                <img src="~/Asset/Images/Games/@Html.DisplayFor(model => model.Game.Image)" alt="ImageJeu" class="img-fluid" />
            </div>
        </div>

    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    window.addEventListener('load', function () {
        if (@Model.IsInFavorites == 1) {
            $("#addToFavoritesBtn").hide();

            // Affichez le bouton "Retirer des favoris"
            $("#remFromFavoritesBtn").show();
        }
        else{
        $("#addToFavoritesBtn").show();

        // Affichez le bouton "Retirer des favoris"
        $("#remFromFavoritesBtn").hide();
        }
    });
    
    $(document).ready(function () {
        // Gérez le clic sur le bouton
        $("#addToFavoritesBtn").click(function () {
            // Obtenez l'ID du jeu à ajouter aux favoris
            var gameId = @Model.Game.Id;  // Remplacez par l'ID réel du jeu

            // Effectuez l'appel AJAX pour ajouter le jeu aux favoris
            $.ajax({
                url: '@Url.Action("AddFav", "Favorits")', // Remplacez "VotreController" par le nom de votre contrôleur
                type: 'POST',
                data: { gameId: gameId },
                success: function (result) {
                    if (result.success) {
                        
                       

                        // Affichez un message de succès si nécessaire
                        //alert("Le jeu a été ajouté aux favoris.");

                        $("#addToFavoritesBtn").hide();

                        // Affichez le bouton "Retirer des favoris"
                        $("#remFromFavoritesBtn").show();
                        document.getElementById("scoreUpdate").innerText = result.score;
                    } else {
                        // Affichez un message d'échec si nécessaire
                        alert(result.message);
                    }
                },
                error: function () {
                    window.location.href = '../../Identity/Account/Register';//louche
                }
            });
        });
    });

    $(document).ready(function () {
        // Gérez le clic sur le bouton
        $("#remFromFavoritesBtn").click(function () {
            // Obtenez l'ID du jeu à ajouter aux favoris
            var gameId = @Model.Game.Id;  // Remplacez par l'ID réel du jeu

            // Effectuez l'appel AJAX pour ajouter le jeu aux favoris
            $.ajax({
                url: '@Url.Action("RemFav", "Favorits")', // Remplacez "VotreController" par le nom de votre contrôleur
                type: 'DELETE',
                data: { gameId: gameId },
                success: function (result) {
                    if (result.success) {
                        alert("Jeu retirer des fav");
                        $("#addToFavoritesBtn").show();

                        // Affichez le bouton "Retirer des favoris"
                        $("#remFromFavoritesBtn").hide();
                        // Affichez un message de succès si nécessaire
                        document.getElementById("scoreUpdate").innerText = result.score;
                        
                    } else {
                        // Affichez un message d'échec si nécessaire
                        alert(result.message);
                    }
                },
                error: function () {
                    alert('Une erreur');
                }
            });
        });
    });





    //verif si deja en fav

   


</script>

Projet/EFCProject/Views/Games/Displayfav.cshtml
@model IEnumerable<EFCProject.Models.Game>


@{
    ViewData["Title"] = "ShowSearchForm";
}
<div class="col-md-10 offset-md-1 align-content-center contente mt-3 ">
<h1>Liste des Jeux en favoris</h1>
<br/>

    <div class="row">
        <div class="col-md-4">
            <div class="form-group col-md-6">
                <label for="SearchInput" class="control-label">Chercher Titre</label>
                <input name="SearchInput" class="form-control" id="searchInput" />
            </div>
            <form asp-action="ShowSearchResults" class="row">
                <div class="form-group col-md-6">
                    <label for="SearchInput" class="control-label">Chercher Support ,Status ou Style</label>
                    <input name="SearchInput" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="SearchInput" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <hr />
</div>


<div class="image-grid contente col-md-10 offset-md-1 mt-3">
    @foreach (var item in Model)
    {
        <div class="list-game">
        <a class="jeu-grid" href="@Url.Action("Details", "Games", new { id = item.Id })" style="background-image: url('@Url.Content("~/Asset/Images/Games/" + item.Image)')">
            <div class="game-pres">
                <div class="row">
                    <div class="col-md-9">
                        <h2>@Html.DisplayFor(modelItem => item.Title)</h2>
                    </div>
                    <div class="col-md-3">
                        <p>@Html.DisplayFor(modelItem => item.Score)</p>
                    </div>
                </div>
                <p>@Html.DisplayFor(modelItem => item.Description)</p>
            </div>
        </a>
        </div>

    }
</div>



<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    $(document).ready(function () {
        // Attacher un gestionnaire d'événement à l'entrée de recherche

        $("#searchInput").on("input", function () {
            // Obtenir la valeur du champ de recherche
            var searchText = $(this).val().toLowerCase();

            // Vérifier si la longueur de la chaîne est supérieure à 3
            if (searchText.length > 3) {
                // Masquer toutes les lignes du tableau
                $(".list-game").hide();

                // Afficher uniquement les lignes qui correspondent à la recherche
                $(".list-game").filter(function () {
                    return $(this).text().toLowerCase().includes(searchText);
                }).show();
            } else {
                // Si la longueur de la chaîne est inférieure ou égale à 3, afficher toutes les lignes
                $(".list-game").show();
            }
        });
    });

</script>

Projet/EFCProject/Views/Games/ShowSearchForm.cshtml
@model IEnumerable<EFCProject.Models.Game>


@{
    ViewData["Title"] = "ShowSearchForm";
}
<div class="col-md-10 offset-md-1 align-content-center contente mt-3 ">
<h1>Liste des Jeux</h1>
<br/>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group col-md-6">
                <label for="SearchInput" class="control-label">Chercher Titre</label>
                <input name="SearchInput" class="form-control" id="searchInput" />
            </div>
            <form asp-action="ShowSearchResults" class="row">
                <div class="form-group col-md-6">
                    <label for="SearchInput" class="control-label">Chercher Support ,Status ou Style</label>
                    <input name="SearchInput" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="SearchInput" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>Trie par :</p>
        </div>
        <div class="col-md-1">
            <a  asp-area="" asp-controller="Games" asp-action="DisplayGamesSorted" asp-route-sortBy="Title"> @Html.DisplayNameFor(model => model.Title)</a>
        </div>
        <div class="col-md-1">
            <a  asp-area="" asp-controller="Games" asp-action="DisplayGamesSorted" asp-route-sortBy="@Html.DisplayNameFor(model => model.Score)"> @Html.DisplayNameFor(model => model.Score)</a>
        </div>
    </div>
    <hr />
</div>

<div class="image-grid contente col-md-10 offset-md-1 mt-3">
    @foreach (var item in Model)
    {
        <div class="list-game">
            <!-- Ajoutez cette div avec la classe list-game -->
            <a class="jeu-grid" href="@Url.Action("Details", "Games", new { id = item.Id })" style="background-image: url('@Url.Content("~/Asset/Images/Games/" + item.Image)')">
                <div class="game-pres">
                    <div class="row">
                        <div class="col-md-9">
                            <h2>@Html.DisplayFor(modelItem => item.Title)</h2>
                        </div>
                        <div class="col-md-3">
                            <p>@Html.DisplayFor(modelItem => item.Score)</p>
                        </div>
                    </div>
                    <p>@Html.DisplayFor(modelItem => item.Description)</p>
                </div>
            </a>
        </div>
    }
</div>


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    
    $(document).ready(function () {
        // Attacher un gestionnaire d'événement à l'entrée de recherche

        $("#searchInput").on("input", function () {
            // Obtenir la valeur du champ de recherche
            var searchText = $(this).val().toLowerCase();

            // Vérifier si la longueur de la chaîne est supérieure à 3
            if (searchText.length > 3) {
                // Masquer toutes les lignes du tableau
                $(".list-game").hide();

                // Afficher uniquement les lignes qui correspondent à la recherche
                $(".list-game").filter(function () {
                    return $(this).text().toLowerCase().includes(searchText);
                }).show();
            } else {
                // Si la longueur de la chaîne est inférieure ou égale à 3, afficher toutes les lignes
                $(".list-game").show();
            }
        });
    });

</script>

Projet/EFCProject/Views/Games/_TextFieldPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if (ViewData["SelectedOption"] as string == "saisirDuTexte")
{
    <label for="champTexte">Champ de Texte:</label>
    <input type="text" id="champTexte" name="champTexte">
}